version: '3.8'

services:
  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'

  celery_worker:
    build:
      context: .
#      dockerfile: public.ecr.aws/z7z4i3p4/zillow_flask_app:latest
    image: public.ecr.aws/z7z4i3p4/zillow_flask_app:latest
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: /start_celeryworker.sh

  celery_beat:
    build:
      context: .
#      dockerfile: public.ecr.aws/z7z4i3p4/zillow_flask_app:latest
    image: public.ecr.aws/z7z4i3p4/zillow_flask_app:latest
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: /start_celerybeat.sh
    depends_on:
      - redis
