version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: zillow_scraper
    command: /start.sh
    volumes:
      - .:/app
    ports:
      - 5010:5000
    depends_on:
      - redis

  redis:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: redis_3.2.1
    command: /install_redis.sh

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: zillow_scraper_celery_worker
    command: /start-celeryworker.sh
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: zillow_scraper_celery_beat
    command: /start-celerybeat.sh
    volumes:
      - .:/app
    depends_on:
      - redis
